// src/components/MarkdownEditor.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import Cherry from 'cherry-markdown/dist/cherry-markdown.core';
import 'cherry-markdown/dist/cherry-markdown.css';
// 动态导入 Mermaid 支持 (推荐)
import CherryMermaidPlugin from 'cherry-markdown/dist/addons/cherry-code-block-mermaid-plugin';
import mermaid from 'mermaid';

// Declare MathJax on window type for TypeScript
declare global {
    interface Window { MathJax: any; }
}

// Define the event this component can emit
const emit = defineEmits<{ 
  (e: 'submit-content', content: string): void;
  (e: 'save-content', content: string): void; // Add save event
  (e: 'cancel'): void; // Add cancel event
}>();

// Define props
interface Props {
  showCancelButton?: boolean;
  isFileListPresent?: boolean; // Add prop to indicate if file list is non-empty
}
const props = withDefaults(defineProps<Props>(), {
  showCancelButton: false,
  isFileListPresent: false, // Default value
});

const registerMermaidPlugin = async () => {
  Cherry.usePlugin(CherryMermaidPlugin, {
    mermaid, // pass in mermaid object
    // 可选：配置 mermaid 行为，参考 mermaid 官方文档
    // theme: 'neutral',
    // sequence: { useMaxWidth: false, showSequenceNumbers: true }
  });
  console.log('Mermaid plugin registered.');
};

async function setupMathJax() {
  // Set configuration BEFORE loading MathJax core
  window.MathJax = {
    tex: {
      inlineMath: [['$', '$'], ['\\(', '\\)']],
      displayMath: [['$$', '$$'], ['\\[', '\\]']]
    },
    svg: {
      fontCache: 'global'
    },
    startup: {
      ready: () => {
        console.log('MathJax is ready (offline).');
        // Tell MathJax to start processing the page
        window.MathJax.startup.defaultReady();
        // Optional: Sometimes a redraw/update is needed after MathJax is fully ready
        // cherryInstance.value?.refresh(); 
      }
    }
  };

  // Dynamically import MathJax core script
  try {
    await import('mathjax/es5/tex-svg.js');
    console.log('MathJax script loaded (offline).');
  } catch (error) {
    console.error('Failed to load MathJax offline:', error);
  }
}

const editorRef = ref<HTMLDivElement | null>(null);
const cherryInstance = ref<Cherry | null>(null);
const markdownContent = ref<string>('');

onMounted(async () => {
  // Setup MathJax first
  await setupMathJax();

  // Register plugins before initializing Cherry
  await registerMermaidPlugin();

  if (editorRef.value) {
    cherryInstance.value = new Cherry({
      id: 'markdown-editor-container',
      value: '', // Clear initial content
      // 其他 Cherry 配置项...
      // 例如，设置编辑器模式、工具栏等
      // See https://github.com/Tencent/cherry-markdown/wiki/Configuration
      engine: {
        syntax: {
          mathBlock: {
            engine: 'MathJax', // KaTeX 或 MathJax
            // 可选：配置 MathJax 或 KaTeX 的参数，例如 macros
          },
          inlineMath: {
            engine: 'MathJax', // KaTeX 或 MathJax
          },
          // 添加默认的 table 配置以解决类型错误
          table: {
             enableChart: false, // 默认禁用 echarts 图表
          },
          // 保留其他默认语法配置...
          list: { 
             listNested: true, // 默认允许列表嵌套
             indentSpace: 2, // 默认缩进
          }
          // ...根据需要添加其他语法默认值以匹配 CherryOptions 类型
        }
      },
      toolbars: {
        theme: 'light', // default 'dark'
      },
      // fileUpload: async (file: File, callback: (url: string, params?: Record<string, any>) => void) => {
      //   // Handle file uploads if needed
      //   console.warn('File upload not implemented');
      //   // Example: upload file then call callback(url)
      // },
      callback: {
        // Fired when content changes
        afterChange: (markdown: string, _html: string) => {
          markdownContent.value = markdown;
        },
      },
    });
  }
});

onUnmounted(() => {
  cherryInstance.value?.destroy();
});

// Function to emit content to the parent component
function submitContent() {
  if (props.isFileListPresent) {
    console.warn("Submit button clicked while file list is present, should be disabled.");
    return; 
  }
  if (cherryInstance.value) {
    const currentContent = cherryInstance.value.getMarkdown();
    // Use the Vue emit defined earlier
    emit('submit-content', currentContent);
    // No need to close window here, parent controls visibility
  }
}

// Function to emit cancel event
function cancelEdit() {
  emit('cancel');
}

// Function to emit save event
function saveContent() {
  if (cherryInstance.value) {
    const currentContent = cherryInstance.value.getMarkdown();
    emit('save-content', currentContent);
  }
}

</script>

<template>
  <div class="editor-page">
    <div id="markdown-editor-container" ref="editorRef" style="height: 500px; border: 1px solid #dcdfe6;"></div>
    <div class="editor-actions">
      <!-- Add Cancel button -->
      <button v-if="props.showCancelButton" @click="cancelEdit" class="button-cancel">返回</button>
      <button @click="saveContent" class="button-save">保存 Markdown</button>
      <button 
          @click="submitContent" 
          class="button-submit" 
          :disabled="props.isFileListPresent" 
          :title="props.isFileListPresent ? '文件列表不为空，无法提交编辑器内容' : '使用此内容进行转换'">
          使用编辑器内容
      </button>
    </div>
  </div>
</template>

<style scoped>
.editor-page {
  display: flex;
  flex-direction: column;
  overflow: hidden; /* Prevent body scroll if editor container itself scrolls */
}

#markdown-editor-container {
  flex-grow: 1;
}

.editor-actions {
  padding: 10px;
  text-align: right;
  background-color: #f8f9fa;
  border-top: 1px solid #dcdfe6;
}

/* Style the button */
.editor-actions button { /* Common styles */
  padding: 8px 15px;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  margin-left: 10px; /* Add some space between buttons */
}

.button-submit {
  background-color: #409EFF;
}

.button-submit:hover {
  background-color: #66b1ff;
}

.button-submit:disabled {
  background-color: #a0cfff; /* Lighter blue for disabled state */
  cursor: not-allowed;
}

.button-cancel {
  background-color: #909399; /* Grey color for cancel */
}

.button-cancel:hover {
  background-color: #a6a9ad;
}

.button-save {
  background-color: #67C23A; /* Green color for save */
}

.button-save:hover {
  background-color: #85ce61;
}

/* Ensure Cherry editor takes full height/width within its container */
:deep(.cherry-markdown) {
  height: 100%;
  width: 100%;
  box-shadow: none; /* Remove default shadow if needed */
}
:deep(.cherry-editor) {
    height: 100%;
}
:deep(.cherry-previewer) {
    height: 100%;
}

</style>

// src/components/MarkdownEditor.svelte
<script lang="ts">
    import { createEventDispatcher } from "svelte";

    const dispatch = createEventDispatcher<{
        "submit-content": string;
        "save-content": string;
        cancel: void;
    }>();

    // Props
    export let showCancelButton: boolean = false;
    export let hasFiles: boolean = false;

    let textareaContent: string = "";

    // Function to emit content to the parent component
    function submitContent() {
        if (hasFiles) {
            console.warn(
                "Submit button clicked while file list is present, should be disabled.",
            );
            return;
        }
        if (textareaContent.trim()) {
            dispatch("submit-content", textareaContent);
        }
    }

    // Function to emit cancel event
    function cancelEdit() {
        dispatch("cancel");
    }

    // Function to emit save event
    function saveContent() {
        if (textareaContent.trim()) {
            dispatch("save-content", textareaContent);
        }
    }
</script>

<div class="editor-page">
    <div class="editor-container">
        <div class="editor-toolbar">
            <h3>Markdown 编辑器</h3>
            <div class="toolbar-buttons">
                <button
                    on:click={() => (textareaContent += "**粗体**")}
                    class="toolbar-btn">B</button
                >
                <button
                    on:click={() => (textareaContent += "*斜体*")}
                    class="toolbar-btn">I</button
                >
                <button
                    on:click={() => (textareaContent += "\n# 标题\n")}
                    class="toolbar-btn">H</button
                >
                <button
                    on:click={() => (textareaContent += "\n- 列表项\n")}
                    class="toolbar-btn">•</button
                >
            </div>
        </div>

        <textarea
            bind:value={textareaContent}
            placeholder="在此输入 Markdown 内容..."
            rows="20"
        ></textarea>
    </div>

    <div class="editor-actions">
        <!-- Add Cancel button -->
        {#if showCancelButton}
            <button on:click={cancelEdit} class="button-cancel">返回</button>
        {/if}
        <button on:click={saveContent} class="button-save">保存 Markdown</button
        >
        <button
            on:click={submitContent}
            class="button-submit"
            disabled={hasFiles}
            title={hasFiles
                ? "文件列表不为空，无法提交编辑器内容"
                : "使用此内容进行转换"}
        >
            使用编辑器内容
        </button>
    </div>
</div>

<style>
    .editor-page {
        display: flex;
        flex-direction: column;
        height: 100%;
        overflow: hidden;
    }

    .editor-container {
        flex-grow: 1;
        display: flex;
        flex-direction: column;
        border: 1px solid #dcdfe6;
        border-radius: 4px;
        overflow: hidden;
    }

    .editor-toolbar {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px 15px;
        background-color: #f8f9fa;
        border-bottom: 1px solid #dcdfe6;
    }

    .editor-toolbar h3 {
        margin: 0;
        color: #303133;
        font-size: 16px;
    }

    .toolbar-buttons {
        display: flex;
        gap: 5px;
    }

    .toolbar-btn {
        padding: 5px 10px;
        border: 1px solid #dcdfe6;
        background: white;
        border-radius: 3px;
        cursor: pointer;
        font-weight: bold;
        color: #606266;
        transition: all 0.2s;
    }

    .toolbar-btn:hover {
        background: #ecf5ff;
        border-color: #409eff;
        color: #409eff;
    }

    textarea {
        flex-grow: 1;
        width: 100%;
        padding: 15px;
        border: none;
        resize: none;
        font-family: "Monaco", "Menlo", "Ubuntu Mono", monospace;
        font-size: 14px;
        line-height: 1.6;
        outline: none;
        background: white;
    }

    .editor-actions {
        padding: 10px;
        text-align: right;
        background-color: #f8f9fa;
        border-top: 1px solid #dcdfe6;
        flex-shrink: 0;
    }

    .editor-actions button {
        padding: 8px 15px;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 14px;
        margin-left: 10px;
        transition: background-color 0.2s;
    }

    .button-submit {
        background-color: #409eff;
    }

    .button-submit:hover:not(:disabled) {
        background-color: #66b1ff;
    }

    .button-submit:disabled {
        background-color: #a0cfff;
        cursor: not-allowed;
    }

    .button-cancel {
        background-color: #909399;
    }

    .button-cancel:hover {
        background-color: #a6a9ad;
    }

    .button-save {
        background-color: #67c23a;
    }

    .button-save:hover {
        background-color: #85ce61;
    }

    @media (prefers-color-scheme: dark) {
        .editor-container {
            border-color: #444;
        }

        .editor-toolbar {
            background-color: #2d2d2d;
            border-bottom-color: #444;
        }

        .editor-toolbar h3 {
            color: #e4e7ed;
        }

        .toolbar-btn {
            background: #3a3a3a;
            color: #c0c4cc;
            border-color: #555;
        }

        .toolbar-btn:hover {
            background: #404040;
            border-color: #409eff;
        }

        textarea {
            background: #2d2d2d;
            color: #e4e7ed;
        }

        .editor-actions {
            background-color: #2d2d2d;
            border-top-color: #444;
        }
    }
</style>
